server:
  port: 8005

spring:
  application:
    name: demo-consumer

  boot:
    # 服务监控
    admin:
      client:
        url: "http://one-monitor:8000"

  cloud:
    # 服务注册
    consul:
      host: one-registry
      port: 8500
      discovery:
        serviceName: ${spring.application.name} # 注册的服务名

  # 链路追踪
  zipkin:
    base-url: http://one-trace:9411/
  sleuth:
    sampler:
      probability: 1  # 采样概率

# 服务监控开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 全部开放
  endpoint:
    health:
      show-details: ALWAYS